### ISSUE TITLE
Bug(Call Animations): Anim doesnt end when call ends

### ISSUE THREAD

**Issue by RockySouthpaw** [project-error/npwd#514]
### Developement Issue

No

### Phone Version

Master branch

### Issue Description

Animation should end but it doesnt.

### Issue Reproduction

1. Open phone
2. Call an invalid number
3. End call

**Comment by itschip** [comment]
@RockySouthpaw Should be fixed in 4b85a4357e61feffba878402da3914f135f8e015

**Comment by Deniel00** [comment]
Hi, 
Still not working in 1.0.5
![kép](https://user-images.githubusercontent.com/12788940/149522414-73f2e1a0-cf3b-4fb7-841b-3ebf75176bca.png)

**Comment by itschip** [comment]
This is fixed in develop. I'll probably release a new patch today.
