### ISSUE TITLE
Bug: my send text message is shown as send by other user

### ISSUE THREAD

**Issue by RuisSoftware** [project-error/npwd#600]
### Development Issue

Unsure

### Phone Version

1.1.6 and 1.1.5 (with my own fix)

### Issue Description

When i send someone a text message, my message is on the right side. The moment i refresh the app all my messages are on the left side instead.

![image](https://user-images.githubusercontent.com/53178920/153646231-0de8bb37-cf89-4d28-8d80-019c273ac6b8.png)

I send "hello", "send by me". The other messages are send by the other player.

### Issue Reproduction

Send a text message to someone
Close the phone
Open the phone and the text thread
Messages are on the left side now

**Comment by itschip** [comment]
@RuisSoftware Is this resolved in develop?

**Comment by RuisSoftware** [comment]
> @RuisSoftware Is this resolved in develop?

Hey big boss. No this issue is still here on develop and 1.1.7

**Comment by itschip** [comment]
I am totally unable to reproduce it with the new database structure. I'd like if anyone else could test the develop branch.

**Comment by itschip** [comment]
Fixed in develop.
