### ISSUE TITLE
Bug: issue on first connection (twitter profile)

### ISSUE THREAD

**Issue by AvaN0x** [project-error/npwd#694]
### Development Issue

Yes

### Phone Version

1.2.7 (Latest)

### Issue Description

When first connecting, the phone will timeout while trying to fetch twitter profile causing the phone to not be able to open anymore.
The account gets created but will only be usable only for the next connection.

### Issue Reproduction

1. Remove the twitter profile of the account you'll test from the database (I tested this with every npwd tables cleared)
2. Connect to the server
3. Twitter profile account fetch will be aborted after 15 secondes : 
![image](https://user-images.githubusercontent.com/27494805/160601499-3225e4e1-fc30-4612-ba5d-287a43c11e9e.png)
And the client side will have this error while trying to do `npwd:fetchTweets` : 
![image](https://user-images.githubusercontent.com/27494805/160601547-16613b32-79f1-4f96-947f-4ed16b669239.png)

**Comment by itschip** [comment]
I think we should add a relation between the profile and each tweet to hinder that any profile gets deleted without deleting the account's tweet.

**Comment by itschip** [comment]
@AvaN0x 1.2.8 contains changes to the Twitter tables which should fix this.

**Comment by AvaN0x** [comment]
> @AvaN0x 1.2.8 contains changes to the Twitter tables which should fix this.

Just trying this and the issue is still occuring on first connection with a freshly imported `import.sql` : 
![image](https://user-images.githubusercontent.com/27494805/161212517-b5d1bac7-6729-49dc-90b7-48ec78ca4201.png)
![image](https://user-images.githubusercontent.com/27494805/161213180-d9fa52f7-823b-443a-8b96-b2a8395d4de6.png)

---

Also I found an issue in the `import.sql` file with the latest commit, you have to create the `npwd_twitter_profiles` table before `npwd_twitter_tweets` : 
```
#1824 - Failed to open the referenced table 'npwd_twitter_profiles'
```
(I can create an issue for this if you prefer)

**Comment by itschip** [comment]
@AvaN0x Can I see your Twitter config? Or is it using the default configuration?

**Comment by AvaN0x** [comment]
@itschip default config for twitter

**Comment by itschip** [comment]
Fixed in develop.

**Comment by AvaN0x** [comment]
> Fixed in develop.

I tested in develop, and I still have the issue of the phone not opening with the slight difference that this time I don't have the "npwd:fetchTweets has timed out" line in client console: 
![image](https://user-images.githubusercontent.com/27494805/161425033-03808bb4-71f3-49ae-a7ed-3a37038154bc.png)
![image](https://user-images.githubusercontent.com/27494805/161425059-c62918f5-ab59-414b-94db-975b69cd02a3.png)

**Comment by itschip** [comment]
@AvaN0x Could you try and delete

**Comment by AvaN0x** [comment]
Yes I'll give it a try a bit later today.

By the way, whenever I try this I always clear everything from npwd on my dev server (DROP every tables and re import them all).

**Comment by AvaN0x** [comment]
Ok so I just tried it with the latest commits from develop and I don't get the issue anymore. Phone opens on first connection after a database cleaning.
Tried two times to be sure and it seems to be fixed.

**Comment by itschip** [comment]
Closing. Reopen if it occurs again.
