### ISSUE TITLE
Bug: using emitMessage export returns an error

### ISSUE THREAD

**Issue by PlouffeLuL** [project-error/npwd#732]
### Development Issue

Unsure

### Phone Version

1.2.94

### Issue Description

When using:
exports.npwd:emitMessage it return a sql? error.

### Issue Reproduction

1. Use the export

### Evidence

[         script:npwd] Error calling system tick function in resource npwd: TypeError: Bind parameters must not contain undefined. To pass SQL NULL specify JS null
[         script:npwd] stack:
[         script:npwd] TypeError: Bind parameters must not contain undefined. To pass SQL NULL specify JS null
[         script:npwd]     at @npwd/resources/dist/server/server.js:33038:21
[         script:npwd]     at Array.forEach (<anonymous>)
[         script:npwd]     at PoolConnection.execute (@npwd/resources/dist/server/server.js:33033:26)
[         script:npwd]     at @npwd/resources/dist/server/server.js:33484:18
[         script:npwd]     at @npwd/resources/dist/server/server.js:33375:42
[         script:npwd]     at processTicksAndRejections (node:internal/process/task_queues:78:11)
[         script:npwd]     at process.runNextTicks [as _tickCallback] (node:internal/process/task_queues:65:3)
[         script:npwd]     at citizen:/scripting/v8/timer.js:263:32

**Comment by Mojito-Fivem** [comment]
Fixed a problem with this export on develop branch, may be related to this. Can you pull develop and see if this helps.

**Comment by PlouffeLuL** [comment]
function Core:SendTxt(playerId, message)
    local phoneNumber = self.Players[playerId].phone_number
    exports.npwd:emitMessage("121-3223", phoneNumber, message)
end

RegisterCommand("textme", function(s)
    Core:SendTxt(s, "penis")
end)

This is the code im using. Didnt do anything special honnestly. Its pretty basic.

**Comment by Mojito-Fivem** [comment]
That will be why it errors out, you're passing the props all wrong. it takes an object like this:
```ts
interface EmitMessageExportCtx {
  senderNumber: string;
  targetNumber: string;
  message: string;
}
```

**Comment by Mojito-Fivem** [comment]
This doesn't seem to be documented so I'll add this to the docs

**Comment by PlouffeLuL** [comment]
At first wizard told me pass it as an array and i was getting the same error. Should it be a table ? Im building the develop branch atm and i'll try.

**Comment by Mojito-Fivem** [comment]
It should be an object as stated above using the interface

**Comment by Mojito-Fivem** [comment]
I pushed an update to the docs with an example

**Comment by PlouffeLuL** [comment]
Yea, i was doing it wrong. Im still getting an error but i assume that because of my configuration and not an issue with the phone.
[         script:npwd] Failed to emit message. Error: Cannot read properties of undefined (reading 'state_id')
Thank you :)
