### ISSUE TITLE
Bug: Unhandled promise failure: TypeError: Cannot read properties of null (reading '2')

### ISSUE THREAD

**Issue by LifeGoal** [project-error/npwd#738]
### Development Issue

Unsure

### Phone Version

1.2.96

### Issue Description

When the resource has started, an error pops up in the server-sided console. I'm unsure if it does anything but I feel like you should know that there is such an error even though it might not be an issue afterall.

I've tested the phone after the error pops out and I can't find any faults what so ever.
I'm on a Linux server. Only comes when the server starts, so nothing else other than that.

Here is the full error:

```
[script:npwd] Error: Unhandled promise failure: TypeError: Cannot read properties of null (reading '2')
[script:npwd]     at parseUri (@npwd/resources/dist/server/server.js:34430:39)
[script:npwd]     at _BootDb.<anonymous> (@npwd/resources/dist/server/server.js:34511:31)
[script:npwd]     at Generator.next (<anonymous>)
[script:npwd]     at @npwd/resources/dist/server/server.js:61:61
[script:npwd]     at new Promise (<anonymous>)
[script:npwd]     at __async (@npwd/resources/dist/server/server.js:45:10)
[script:npwd]     at _BootDb.doesPlayerTableExist (@npwd/resources/dist/server/server.js:34510:16)
[script:npwd]     at _BootService.<anonymous> (@npwd/resources/dist/server/server.js:34585:58)
[script:npwd]     at Generator.next (<anonymous>)
[script:npwd]     at @npwd/resources/dist/server/server.js:61:61
```

Haven't changed anything really other than just set it up by your documentation. No changes to the code.

### Issue Reproduction

1. Start the server
2. Bang, there it is instantly

(Only comes when server starts)

### Evidence

[Picture of error (Link to Imgur)](https://i.imgur.com/nrLM2bO.png)

**Comment by Mojito-Fivem** [comment]
What does your config look like?

**Comment by LifeGoal** [comment]
I've implemented QBCore to the phone now so it looks like this. Still has the same error.

```{
  "PhoneAsItem": {
    "enabled": true,
    "exportResource": "qb-npwd",
    "exportFunction": "HasPhone"
  },
  "general": {
    "useResourceIntegration": true,
    "toggleKey": "f2",
    "toggleCommand": "phone",
    "defaultLanguage": "en"
  },
  "profanityFilter": {
    "enabled": false,
    "badWords": ["esx"]
  },
  "database": {
    "useIdentifierPrefix": false,
    "playerTable": "players",
    "identifierColumn": "citizenid",
    "identifierType": "license",
    "profileQueries": true,
    "phoneNumberColumn": "phone_number"
  },
  "debug": {
    "level": "error",
    "enabled": true,
    "sentryEnabled": true
  }
}```

**Comment by itschip** [comment]
@LifeGoal still an issue? Have you tried setting `useIdentifierPrefix` to `true`?

**Comment by xxstreetstylexx** [comment]
Hey all, 

same issue here. Take a look into the Docs and figure out that set mysql_connection_string in docs is in other format than in fivem config. 

try to transform the fivem connection string to the expected one.

fivem expect server=xxx;database=xxx; (...) like on docs: https://www.connectionstrings.com/mysql/

npwd seems to be expect it in form mysql://user:pass@server/db? (...)

if i change it to mysql:// the server wont be able to connect but it seems that nwpd works (no error in log relatet to that) and this error disappears. oxmysql dont can connect even the password is uri encoded.

**Comment by itschip** [comment]
We should support both. I'll look into it, but good to know that url connection strings works, somwhat. Can you show me the connection string you tried that caused the error, @xxstreetstylexx ?

**Comment by xxstreetstylexx** [comment]
@itschip 

This one dont Work:
set mysql_connection_string "server=127.0.0.01;database=fivem;userid=root;password=<PASSWORDHIDDEN>"

This one dont give any type of issue for NPWD but for oxmysql 
set mysql_connection_string "mysql://root@localhost/fivem?charset=utf8mb4&password=<PASSWORDHIDDEN-URIENCODED>"

[      script:oxmysql] Error: Unable to establish a connection to the database!
[      script:oxmysql] [Error: Access denied for user 'root'@'localhost']

This one also dont work:
set mysql_connection_string "mysql://root:<PASSWORDHIDDEN-URIENCODED>@localhost/fivem?charset=utf8mb4"

**Comment by itschip** [comment]
@LifeGoal are you able to reproduce this in 1.5.0?

**Comment by TheKronoss** [comment]
I tried using 1.5.4 now, and get the same error, I am using oxmysql

**Comment by TheKronoss** [comment]
@itschip I can reproduce this issue when using an # in the password it won't work. If I remove the # from the password in the db and in the connection string, everything works fine.

**Comment by thefalconrain** [comment]
I ran into this exact error and was able to resolve it.

**Solution:** Change your database password. Make sure that you DO NOT have any symbols in your password.

**Problem Explanation:** my database was connecting successfully using the server setup example connection strings in the server.cfg. I think the error occurs somewhere in NPWD trying to grab this string from the server.cfg. The special character in the password breaks something. In my example this had a # used.

Error prior to removing symbol from password
![image](https://github.com/project-error/npwd/assets/143903353/118da3c0-d484-4098-977a-870ed7905f0c)


**How:** Run this command in MariaDB to set a new password
```
ALTER USER 'root'@'localhost' IDENTIFIED BY 'YourDesiredPasswordHere';
flush privileges;
exit;
```
